### ISSUE TITLE
support for non-archives

### ISSUE THREAD

**Issue by afeld** [concourse/archive-resource#3]
I am interested in using this Resource for normal HTTP requests, which would be a very small change. Would you be open to it supporting both, if I were to send a pull request? It could either take an option for `compression: tgz`, or [try and do a best guess](http://stackoverflow.com/questions/2001709/how-to-check-if-a-unix-tar-gz-file-is-a-valid-file-without-uncompressing). Thoughts?

**Comment by vito** [comment]
I don't think we'll be extending this resource much. It's really only intended for supporting `fly execute`.
