### ISSUE TITLE
Does not work, when only tagged workers are available

### ISSUE THREAD

**Issue by friegger** [concourse/archive-resource#7]
With a concourse where all workers are tagged and there is no untagged worker, one-offs with `fly execute` do not work. Apparently the implicitly used archive resource does not support tagging. 

The error we get:
```
no workers satisfying: resource type 'archive'

available workers:
...
```

**Comment by chendrix** [comment]
Hi there @friegger have you been able to reproduce this in more recent versions of concourse? I believe we added support for running `fly -t <target> e --tag <tag>`

I'm going to close this, but feel free to re-open in https://github.com/concourse/concourse/issues/new if you are still having trouble.

**Comment by friegger** [comment]
@chendrix Tested with fly `3.0.1`. Still getting `no workers satisfying: resource type 'archive'` despite `--tag=<worker-tag>`. Opened concourse/concourse#1208
