### ISSUE TITLE
docs need an update - authorization is missing

### ISSUE THREAD

**Issue by EugenMayer** [concourse/archive-resource#8]
`authorization` is missing

```
      authorization:
        user:
        password:
```

**Comment by topherbullock** [comment]
This resource isn't really meant for use in pipelines, and is used internally by `fly execute`
```
NOTE: This resource is only intended for use in fly execute (it's how your inputs get uploaded). It won't work in a pipeline because check never yields any valid versions. 
```

There's a community curl resource if you want to download files from a url https://github.com/pivotalservices/concourse-curl-resource
